apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: postgres
    database: metrics_db
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 10
      timescaledb: true
      postgresVersion: 1400
    secureJsonData:
      password: "password"
    editable: true