global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'go-metric-watcher'
    static_configs:
      - targets: ['localhost:2112']
#
#  - job_name: 'metrics-api'
#    static_configs:
#      - targets: ['metrics-api:8080']
#    metrics_path: '/api/v1/metrics'