global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-api'
    static_configs:
      - targets: ['metrics-api:8080']

remote_write:
  - url: "http://prometheus-adapter:9201/write"

remote_read:
  - url: "http://prometheus-adapter:9201/read"