name: Docker Build and Push

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push metrics-api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deployments/Dockerfile
          target: metrics-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/metrics-api:${{ github.sha }}

      - name: Build and push metrics-collector
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deployments/Dockerfile
          target: metrics-collector
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/metrics-collector:${{ github.sha }}

# 현재는 사용되지 않는중 이미지만 docker hub 에 올려놓는다

